### ISSUE TITLE
Broken on Hub 7/28 Beta 2

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/logreader#1038]
![Screenshot_20231110_160529](https://github.com/nextcloud/logreader/assets/551757/13bd9b04-6310-46c4-b548-07f6d23315f6)

you might spot the menu behind the left sidebar. Similar problem on the bottom left. Shift-refresh does not fix it, most javascript functions don't seem to work (... menu, opening more info etc)

**Comment by susnux** [comment]
Will be fixed with https://github.com/nextcloud/logreader/pull/1037
