### ISSUE TITLE
Broken UI for selecting log level

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/logreader#1048]
I found that the UI of selecting the log level is a bit broken: the button to upload the log file is not shown according to the UI theme.

![image](https://github.com/nextcloud/logreader/assets/5199030/5116b68b-d9dd-4c6f-a26b-2999f39e19d3)

Please, fix it.

**Comment by Antreesy** [comment]
Last version of Logreader written in react is Nextcloud 27.1.11 (End of life was at 2024-06-25)
