### ISSUE TITLE
Log reader displays error "Could not fetch new entries" even though it can download log file

### ISSUE THREAD

**Issue by nodje** [nextcloud/logreader#1077]
I just migrated to 28.0.0 but I'm not sure it's related.

I can't display the log even though I can download the file in Log Reader Settings-> Download.
Meaning AFAIK, there's no permission issue, and the file exists and is accessible.

I'm using default option, there's no configured option in config.php except for `'loglevel' => 2,`

I have a properly rotated `nextcloud.log` file in the configured `datadirectory` 

I can't see the GUI error "Could not fetch new entries" in the log file itself though.
Enabling the Audit Log did not bring any related logs.

**Comment by tzerber** [comment]
https://github.com/nextcloud/logreader/issues/1073#issuecomment-1855974097 and below might help ;)
