### ISSUE TITLE
Error on open the app

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/logreader#1134]
### Steps to reproduce
1. Go to admin panel > Protocol
2. Error appears but messages are shown after some seconds
3.

### Expected behaviour
no error

### Actual behaviour
error
![broken](https://github.com/nextcloud/logreader/assets/1473674/ea063166-e08b-43f8-b003-2c8ab5593ae5)

### Server configuration
**Operating system**:
Ubuntu 22.04

**Web server:**
Apache 2.4.58

**Database:**
MariaDB 10.11

**PHP version:**
PHP 8.3

**Nextcloud version:** (see Nextcloud admin page)
28.0.1 and now 27.0.2 RC4

**Where did you install Nextcloud from:**
fresh from your website

**List of activated apps:**
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.4
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - collectives: 2.9.2
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - groupfolders: 16.0.3
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.1.0-beta3
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.2
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0

**Nextcloud configuration:**
 "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.131"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.3",
        "overwrite.cli.url": "http:\/\/192.168.1.131",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "de",
        "maintenance_window_start": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "",
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }

### Client configuration
**Browser:**
Microsoft Edge

**Operating system:**
Windows 11

**Comment by joshtrichards** [comment]
Check your browser ad blocker :)

**Comment by Dennis1993** [comment]
Ah you are right :D
Can we fix that?

**Comment by joshtrichards** [comment]
Good question. Since it's a false positive it depends on whether there is something reasonable we can do on our end or not. If it's something silly like blocking because the keyword `log` is in the URL or something than we're probably stuck. 

Feel like poking around and see what rule is actually blocking things?
