### ISSUE TITLE
logreader doesn't work shows nothing

### ISSUE THREAD

**Issue by feadraug** [nextcloud/logreader#1232]
### Steps to reproduce
1. truenas core
2. nextcloud plugin in a jail, updated through nextcloud up to latest available there 27 - 28.04 - 28.0.5 (web check shows 29.0.0.19), sometime shows "Downgrading is not supported and is likely to cause unpredictable issues (from 28.0.5.1 to 28.0.4.1) "
3. logging page in admin setup is empty totally

### Expected behaviour
i would like to see some logs there

### Actual behaviour
i could say, i have never seen there anything since i installed NC

### Server configuration
-->usefull

**Operating system**:
Freebsd 13.1
**Web server:**

**Database:**
mysql
**PHP version:**
8.2.18 
**Nextcloud version:** (see Nextcloud admin page)
28.0.5
**Where did you install Nextcloud from:**
community probably

**List of activated apps:**
Enabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_reminders: 1.1.0
  - files_trashbin: 1.18.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - activity: 2.20.0 (installed 2.20.0)
  - calendar: 4.7.1 (installed 4.7.1)
  - circles: 28.0.0 (installed 28.0.0)
  - comments: 1.18.0 (installed 1.18.0)
  - contacts: 5.5.3 (installed 5.5.3)
  - contactsinteraction: 1.9.0 (installed 1.9.0)
  - dashboard: 7.8.0 (installed 7.8.0)
  - deck: 1.12.2 (installed 1.12.2)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.18.0)
  - files_pdfviewer: 2.9.0 (installed 2.9.0)
  - files_sharing: 1.20.0 (installed 1.20.0)
  - files_versions: 1.21.0 (installed 1.21.0)
  - firstrunwizard: 2.17.0 (installed 2.17.0)
  - groupfolders: 16.0.6 (installed 16.0.6)
  - mail: 3.6.0 (installed 3.6.0)
  - nextcloud_announcements: 1.17.0 (installed 1.17.0)
  - notes: 4.10.0 (installed 4.10.0)
  - photos: 2.4.0 (installed 2.4.0)
  - recommendations: 2.0.0 (installed 2.0.0)
  - related_resources: 1.3.0 (installed 1.3.0)
  - sharebymail: 1.18.0 (installed 1.18.0)
  - spreed: 18.0.7 (installed 18.0.7)
  - support: 1.11.1 (installed 1.11.1)
  - survey_client: 1.16.0 (installed 1.16.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.18.0)
  - text: 3.9.1 (installed 3.9.1)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.8.1)
  - weather_status: 1.8.0 (installed 1.8.0)
  - 
**Nextcloud configuration:**
```
<!--
<?php
$CONFIG = array (
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/local/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/usr/local/www/nextcloud/apps-pkg',
      'url' => '/apps-pkg',
      'writable' => false,
    ),
  ),
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 1,
  'log_type' => 'file',
  'log_rotate_size' => 104857600,
  'logtimezone' => 'somewhere',
  'log_query' => false,
  'cron_log' => true,
  'logdateformat' => 'F d, Y H:i:s',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'one-click-instance' => true,
  'one-click-instance.user-limit' => 100,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
  ),
  'passwordsalt' => 'salt',
  'secret' => 'secret',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'trusted_domains1',
    2 => 'trusted_domains2',
    3 => 'trusted_domains3',
  ),
  'datadirectory' => '/usr/local/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '28.0.5.1',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'user',
  'dbpassword' => 'somepwd',
  'installed' => true,
  'instanceid' => 'hopethiscanbedeletedhere',
  'updater.secret' => 'ups',
  'maintenance' => false,
  'maintenance_window_start' => 1,
  'theme' => '',
  'twofactor_enforced' => 'true',
  'twofactor_enforced_groups' => 
  array (
    0 => 'user1g',
    1 => 'user2g',
  ),
  'twofactor_enforced_excluded_groups' => 
  array (
  ),
);
```

### Client configuration

**Operating system:**

#### Browser log

btw i suspect rw rules etc through file/folder access but that was a default installation

help pls

**Comment by jmechnich** [comment]
Could you check using the “Network” tab in your browser’s “Developer Tools” that all components are loaded successfully?
I had a similar issue where the page was initially empty, but was populated after a few seconds due to a refresh triggered by JS.
The reason for me was that I am using a blocker browser add-on (uBlock Origin) that prevented one JS file from loading.

**Comment by feadraug** [comment]
as a solution
in a jail
usr/local/etc/nginx/mime.types
add string
application/javascript                           mjs;
restart jail
now logging works,
error Please check manually if your webserver serves `.mjs` files using the JavaScript MIME type. gone
huh
