### ISSUE TITLE
Strings in main and 3-dots menu are not displayed in selected language.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/logreader#160]
## Expected behavior
All kind of text strings should be displayed in the selected language.

## Current behavior
The following texts are currently not translated into German language, although correct translations exist:
- Logging
- Log levels
- Log content
- Live update
- Download logs

![20190402_nc_settings_logging_translation_of_-Log_content-Live_update-Download_logs-](https://user-images.githubusercontent.com/2572764/55459483-f9eb4180-55ef-11e9-8f35-8f7543e3b4ec.png)

## Steps to reproduce
1. open the settings dialog
2. navigate to Administration > Logging

#### Server Configuration
OS: Linux 3.16.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 15.0.5
Logreader app version: 2.0.0

#### Client Configuration
Browser: Mozilla Firefox 66.0.2
Operating system: Windows 10

**Comment by susnux** [comment]
Fixed with Nextcloud 28, see https://github.com/nextcloud/logreader/pull/936
