### ISSUE TITLE
Error while using logreader

### ISSUE THREAD

**Issue by fjvt** [nextcloud/logreader#244]
### Steps to reproduce
Use nextcloud and periodically these errors will be shown ...

### Expected behaviour
No errors

### Actual behaviour
Errors shown

## Server configuration detail

**Operating system:** Linux 4.15.18-20-pve #1 SMP PVE 4.15.18-46 (Thu, 8 Aug 2019 10:42:06 +0200) x86_64

**Webserver:** nginx/1.14.2 (fpm-fcgi)

**Database:** mysql 10.3.15

**PHP version:** 

7.3.4-2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - bruteforcesettings: 1.4.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "quota_include_external_storage": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "",
    "loglevel": 0,
    "maintenance": false,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "log_type": "file"
}
```
</details>

**Are you using external storage, if yes which one:** Local (via OS mounted NFS)

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Operating system:** Win 10

## Logs

<details><summary>Web server error log</summary>

n/a 

</details>

<details><summary>Nextcloud log</summary>

```
Error	implode(): Invalid arguments passed at ***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#93		2019-08-28T12:21:10+0200
Error	Array to string conversion at ***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#93		2019-08-28T12:21:10+0200
Error	Undefined index: type at***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#52		2019-08-28T12:21:10+0200
Error	Undefined index: class at ***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#52		2019-08-28T12:21:10+0200
Error	implode(): Invalid arguments passed at ***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#93		2019-08-28T12:21:10+0200
Error	Array to string conversion at ***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#93		2019-08-28T12:21:10+0200
Error	implode(): Invalid arguments passed at ***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#93		2019-08-28T12:21:10+0200
Error	Array to string conversion at ***REMOVED SENSITIVE VALUE***/nextcloud/apps/logreader/lib/Log/Formatter.php#93		2019-08-28T12:21:10+0200
Debug	OC\AppFramework\Middleware\Security\Exceptions\NotLoggedInException: Current user is not logged in		2019-08-
```
</details>

<details><summary>Browser log</summary>

n/a

</details>

**Comment by joshtrichards** [comment]
I suspect this has been fixed (long ago) based on circumstantial evidence, but I can't say with more certainty without a fuller stack trace. Let us know if you're still experiencing this.

**Comment by susnux** [comment]
Can not reproduce this with Nextcloud 26, 27 or 28.
If you still experience this error please reopen the issue.
