### ISSUE TITLE
value in config.php is not respected

### ISSUE THREAD

**Issue by enoch85** [nextcloud/logreader#246]
### Steps to reproduce
1. Do a fresh install of Nextcloud 16.0.4
2. Change the default log path to `/var/log/nextcloud/nextcloud.log` in `config.php` according to https://docs.nextcloud.com/server/16/admin_manual/configuration_server/config_sample_php_parameters.html#logging
3. Set correct permissions (www-data) for folder and log file.
4. Create a failed login attempt

### Expected behaviour
Log should end up in the path set in `config.php`

### Actual behaviour
The `config.php` entry is not respected and it still tries to create a log in the datadir path.

## Server configuration detail

**Operating system:** Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, json, igbinary, apcu, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, redis, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/templates/layout.public.php] => Array
                        (
                            [expected] => 27f754d16782bd1482bdf40a8677dcff90d80cf47206c948421e416e02d797b4048503bf79c78f0d563f6b8817027f6eb985985357a48e8600e325c94dfdf299
                            [current] => 7b3743244b6120848988318c0470391ffae1af0349435f883934591ddfd8838da0bef223a46663d0a20ef13c869b1e0010fd82abcb315ff846af65d0812b6683
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.17.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.100.36",
        "ubuntu"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "https:\/\/ubuntu\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "loglevel": "3",
    "logfile": "\/var\/log\/nextcloud.log",
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "1800",
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 180",
    "versions_retention_obligation": "auto, 365",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "logtimezone": "Europe\/Stockholm",
    "htaccess.RewriteBase": "\/",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
[index] Error: Exception: Error while opening /mnt/ncdata/nextcloud.log at <<closure>>

0. /var/www/nextcloud/apps/logreader/lib/Controller/LogController.php line 61
   OCA\LogReader\Log\LogIteratorFactory->getLogIterator("11111")
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\LogReader\Controller\LogController->get(50, 0, "11111")
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\LogReader\Controller\LogController {}, "get")
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\LogReader\Controller\LogController {}, "get")
4. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\LogReader\ ... r", "get", OC\AppFramework\ ... {}, {_route: "logreader.log.get"})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "logreader.log.get"})
6. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "logreader.log.get"})
7. /var/www/nextcloud/lib/base.php line 975
   OC\Route\Router->match("/apps/logreader/get")
8. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /apps/logreader/get?offset=0&count=50&levels=11111
from 10.10.0.2 by daniel at 2019-09-04T06:47:59+02:00
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by enoch85** [comment]
Second time it worked. Strange.

**Comment by enoch85** [comment]
OK, so it actually doesn't work.

It gets logged OK in the actual log file, but it doesn't show up in the GUI.

```
root@ubuntu:/var/log/nextcloud# ll
total 12
drwxr-xr-x  2 root     root     4096 sep  4 08:16 ./
drwxrwxr-x 13 root     syslog   4096 sep  4 08:20 ../
-rw-r-----  1 www-data www-data    0 sep  4 08:06 audit.log
-rw-r-----  1 www-data www-data  349 sep  4 08:29 nextcloud.log
-rw-r--r--  1 root     root        0 sep  4 08:16 update.log
root@ubuntu:/var/log/nextcloud# cat nextcloud.log 
{"reqId":"LgVR3TcfwIWNEfd8I1HE","level":2,"time":"2019-09-04T08:29:55+02:00","remoteAddr":"192.168.2.10","user":"--","app":"core","method":"POST","url":"\/login?clear=1","message":"Login failed: 'daniel' (Remote IP: '192.168.2.10')","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.4.1"}
```

![Screenshot from 2019-09-04 08:33:54](https://user-images.githubusercontent.com/4511254/64231043-c427ed00-ceee-11e9-807b-d2bf825267f4.png)

**Comment by enoch85** [comment]
It also downloads the correct file when hitting "Download logs", but still nothing in GUI. Tried to set 777 permissions, but no change.

**Comment by joshtrichards** [comment]
I'm unable to reproduce this in v26.0.1. Can we close this out?

As an aside I noticed your provided config says
```
  "logfile": "\/var\/log\/nextcloud.log",
```

Didn't you mean for it to be:

```
  'logfile' => '/var/log/nextcloud/nextcloud.log'
```

in order to match your reproduction steps? ;-)

If the former really was the config, I'm more curious how you got *any* entries, hah. 🤔 Weird

**Comment by enoch85** [comment]
This is several years old. :)

Closing.
