### ISSUE TITLE
No translated descriptions

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/logreader#263]
- Translation of descriptions is missing:

![obraz](https://user-images.githubusercontent.com/47037905/66124652-463a2d00-e5e5-11e9-9ea2-5613b7fa9c5f.png)

Translation is in Transifex and l10n.

- Missing to translate the description in Transifex:

1. Load log file...
2. Invalid log file
3. Debug
4. Info
5. Warning
6. Error
7. Fatal

App:
Nextcloud 17.0.0
Log Reader 2.2.0

**Comment by rakekniven** [comment]
Still the same with v2.4.0 and server v19.0.2

**Comment by Valdnet** [comment]
@rakekniven Some time has passed and there are no changes. Apparently the problem is not that important  :smiling_imp:.

@icewind1991 and @MorrisJobke Is there a chance it will be corrected?

**Comment by Valdnet** [comment]
The text strings indicated by rakekniven refer to the "settings" directory. In my opinion, they should refer to the "logreader" directory.

Does anyone deal with this repository at all? There are a lot of shortcomings that still persist in the NC 22 version.

**Comment by rakekniven** [comment]
Let's try to change that and merge if no one is responding.

**Comment by Valdnet** [comment]
Currently, there is still work to be done:

https://github.com/nextcloud/logreader/blob/bf5d145664738efbc1d73928c01a5ee0295ee6b4/js/Components/LogLevel.js#L4
https://github.com/nextcloud/logreader/blob/0ab708a711f67678f49a3b921abcc3fc633e89a7/js/Components/LogUploader.js#L8
https://github.com/nextcloud/logreader/blob/0ab708a711f67678f49a3b921abcc3fc633e89a7/js/Components/LogUploader.js#L21
