### ISSUE TITLE
missing resource file from the 3.0 release

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/logreader#29]
I installed the latest logreader from the release tab like it told me to. Copy the whole folder and did one occ upgrade. Everything went fine until i wanted to visit the logreader there I get the error message 

> Could not find resource file "/apps/logreader/js/../build/main.js"

There is not /logreader/js/... inside the release 3.0 tarball inside the 1.2 there is.
How can I fix this?

**Comment by icewind1991** [comment]
Seems like I made a packaging error, re-uploaded the release, can you retry with the re-uploaded release

**Comment by mightyBroccoli** [comment]
It is working properly now. Yeah there was just the js folder missing.
thank you.
