### ISSUE TITLE
Code integrity fail with NC11

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/logreader#30]
I'm using the latest release from the git with NC11 and am getting a code integrity check failure. Here is the output from NC. Thanks.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- logreader
	- INVALID_HASH
		- appinfo/app.php
		- appinfo/info.xml
		- appinfo/routes.php
		- build/main.css
		- build/main.css.map
		- build/main.js
		- build/main.js.map
		- controller/logcontroller.php
		- controller/pagecontroller.php
		- css/app.css
		- img/app.svg
		- js/App.js
		- js/Components/Exception.js
		- js/Components/Exception.less
		- js/Components/LogTable.js
		- js/Components/LogTable.less
		- js/Components/ToggleEntry.js
		- js/Providers/LogProvider.js
		- js/index.js
		- templates/index.php
	- EXTRA_FILE
		- img/app.png
		- README.md

Raw output
==========
Array
(
    [logreader] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/app.php] => Array
                        (
                            [expected] => 3bb835c50454e7771673df7cfa079f1e3165b7ad13bee6c79f60e1dc049efb169b8a2dca21ede7f0c35d94bfbebb8089788adfbe93d9b46f877597f1366897cb
                            [current] => e82a45b7ceafdce6e8eb24a8231f0aee9c56710d43cbcef4de4f09a8690106d77f337407037e974ceeb9f8b3c88e446b5ef6a4ee1d46a83ff2e1c4fa5d01386c
                        )

                    [appinfo/info.xml] => Array
                        (
                            [expected] => e7dac0ce0de14c4a458c698fb79b005b96d4bb6aef8696a0d0c8317cae35fd641560aa0bd39bb3c54796c95a0c6b890951c2218ca3381bbd3100fd7eeaed8537
                            [current] => 2269773b215ccd99bccff3c0ffe5951d0c4334dc5fe03b77be93926c772680a8445dcd120c7b090ba07aed92b695679d5f71512174bb20286ad4eabf2222940a
                        )

                    [appinfo/routes.php] => Array
                        (
                            [expected] => 6c0cde94c1ab874b465b5439b9ec74aa2ee74ed6d3567111b3faf83c5fc20b5e9b584df6593e71368908e8594f363a9401ae394623eba50ef7394659df7fb8e0
                            [current] => 4976aee8a91b4867c36f566b4ddf2b3474edf3dd8fbf838a821230858899bf541c589d57e9c11c5a96916c282dab57dd5c456acace1b0cceb89b87fb97131c84
                        )

                    [build/main.css] => Array
                        (
                            [expected] => 56761d3c8fa99ec439907beda426aa9afd83162ae02ce8f5e15f28001f3bdae4845805e29ab149f31d8eb55452fe7edcd2bc927079cc3a12c75dc230a7649140
                            [current] => ab3610b9dbddf0791d12a0ea094c90d16bd9085b778968fca2e56d41a660cfec810c72bf8373c5d0546f78df820f5f94e4f7ce079268aab4be4b6804f78ff5b8
                        )

                    [build/main.css.map] => Array
                        (
                            [expected] => ab1198ecf3a4da50e97fa2d9a2d5347910bc03178dd16794ca433a449ce5dbc3df9236f5069c9641986b60abe74e0184c11b2216ceac0138a36e32e14dccf5a9
                            [current] => 09dc2593205528e30ff3cb4937a59b9f33c8e0801f55dbc8a25ead898e42185b6087d94327329368394525b85ca78f4c6237366dc7d4a1cf7b06e34ff1131dfe
                        )

                    [build/main.js] => Array
                        (
                            [expected] => 867f6c550134ec77ac19ba4fee5c055b2588449fd6e1d28088f19799e832836c57bff049739b6cdfd3e01080030314bdce9f36f0c8a493be8c678ca4249f5441
                            [current] => 804c0c3f0c92df6012272290b2cfbc4300e9eda4a088d0652499afaa216617c6835bb56f67f63b1e4dc2be3c25832cb0095f4384e819cc3f6a206564fd35b433
                        )

                    [build/main.js.map] => Array
                        (
                            [expected] => 68a06094eea4098158b968dc25b0609eb6354b4618b6ea1e3b44d809686881bb668f16da82e5ace92b9e9f20648ee46c4496ff922138efeaa85dfbfacd2b9de9
                            [current] => 2c73513a6c2775c5f47a682deaeaf9451d800cef8446a1576bdb7c34f2cc3ecb36a4a65ffb7b1e5cca6120992e84b868b0ffd871714a5cdb90349816651aebe0
                        )

                    [controller/logcontroller.php] => Array
                        (
                            [expected] => 3aa27fae7d064fddf5129bcd72db3a770277399ad28ce630343e2bdcc46791a40bc596f1ec1a27a4558d96728d24c7a661b1673f6b7223b5c09eabb0c40a324c
                            [current] => 7e64930c61d412fb67019a4a2ffb2f07fec2360c74e953480fe7e811e6f21f85478046b4cb153e251e96f615cd4776595975570ad9d16a844012cd422488495e
                        )

                    [controller/pagecontroller.php] => Array
                        (
                            [expected] => 8d0420ed341ed2d447cd7fa8c09f38652d6a30857aece04ea35408ab4370f6ebfe09daf369c9defcb92f9e73195782dfbce2fde4afdb89ee4be338c2c0375424
                            [current] => f7629f54e27b7e1756c0f8992dc9da21994115f6db2033683773872c7b7c6fb03783105e38766326f556cecffee665216139abaf90d38a2c13bcaa31af0cbb98
                        )

                    [css/app.css] => Array
                        (
                            [expected] => 3a1831b8a394bd50c9b661d328c2b65eca0e5ea6b5d25d391316846f7e571913569d6424b5fa51ceadae25f96dfb46edec66962ea6bb5792a5ea952bc207eeb0
                            [current] => 6ea576d8d4be77a8913f603d585c1606509a7b8a38c48af767e26fdb86d36edabe0860370669359f4ebedb8c85a0d795f400243668d54202243f6823ccc505da
                        )

                    [img/app.svg] => Array
                        (
                            [expected] => a88eb1748e98e35a400e3baea0894423965c3ccb3192f770b2deb976727470c7f96ef64edf9cda66bfabf38b84e5f11d52d0114e234c3bcae0e1a19887ac9a1e
                            [current] => bd1e96db071c32880202b3810b4dd5e0d629818e48d7fe1f93222c723fdcc842dce3cee92d317e13cd72b1a587debcdbcf143aa741bdb0d4bf4d25aa666ee440
                        )

                    [js/App.js] => Array
                        (
                            [expected] => c59c40cc4c34d7fe4874e9630e6a0039a0d3e5c4313d5eb439f35f4f7dd66ec2aef456b6794e3e6c7c56e434ab8be1a00c14a12251474883392b1d10e0ebb854
                            [current] => 0f869c142a5ef96d023fffdaa773a23954d586a6c92d4df24ccd9550eb0022394be6a9617cba0c422cf5ca33c5681fce01628aa5340e9764e8f5617682e7d73c
                        )

                    [js/Components/Exception.js] => Array
                        (
                            [expected] => 2254737771fddb03bec75e294dcc7f5c971350e0517c2e78128efea684c9f672342358978b65e9975d7c0b2fdcc69b097233b22ecc703bc2be9884214f8115d4
                            [current] => 99af99ea714add3dcb08b152e72634ed658773346b91219a9e3227784a78fd0b16bff5a1c46d199a445f2cb8960837c4b9079d5ee73a9d4859ac305b84a04267
                        )

                    [js/Components/Exception.less] => Array
                        (
                            [expected] => 80aa41afb2101fc55566e2fa90fda89fce956c5f632a182e93f252d25df4b6e2d30d9edb8b1f8155782dc1241273dbc8e05c7c0e563ad64c02a497bc819b5f06
                            [current] => 56e5c537cef3f76c7728e52a504b8f4fcafade798f66a1c5d8fa836f572e5c0e0a946ba8a49eeeb0ee13922e175182bce75cc783a82842d95386c6e22283ee07
                        )

                    [js/Components/LogTable.js] => Array
                        (
                            [expected] => 89d4f2da567a8d135609964b4ac5eedc7e672ebbd0ff712557fd0f38bfbe6ab1258a09d6d6a384b728143725b8f1b91608dc2a581651ce64d8e9be5eca553144
                            [current] => 08542aed2ee9d4ed7c06c3e817da3aad9f52c411cae0feea571731616b66349a5005be1864e8a83a078f0b5260f719da2a2627c295f3309f078b4ad09a4289e1
                        )

                    [js/Components/LogTable.less] => Array
                        (
                            [expected] => be6cd45392d79f10d61b3b8e3970106a19945ec5b6642e5c887822a6b7b69651ce23dfce1fc520a5ca55d6d123274f26f27548019cfee4201941320be1832bde
                            [current] => 1116f605a4ec5943726863a3a380b5c3378d0383f0ae70fe1924105415ef8183e375263a7789b01ade5a0713cd7f61918b9ffd0e11858ca18cf6de2348eadb7f
                        )

                    [js/Components/ToggleEntry.js] => Array
                        (
                            [expected] => a6ae1bb704e579188027d8354f18923c74fa93a137dfa264d755727c13feb5af5a0f9d171a6f8f3a9c83612c52146912996a08a0e48927674d2b22d6faeb455d
                            [current] => 3838562e499cbad8fb3a10c8895b500647bc4346e3c8d578512abc2287c6cfb467f2d936a76edb7d407f7519711b6a68ce0ade4dbec3b197b5eb50b091f8faaf
                        )

                    [js/Providers/LogProvider.js] => Array
                        (
                            [expected] => 77329aff0f84f6dabeb80a458800823b95f7f7ab3861397975d3e6c7e6ab533d456714d97c072e1209a76b433e2340e43b247d29b30f65f18903ee13ffb71fbc
                            [current] => 981b6a69287e8ed606d7e8c05f21776698798c65a7953dacf2f2bcca1dc492b0be4bf45335b9a7daee9d628b9241e6116fa5705acd277c8283d1cba372ac12af
                        )

                    [js/index.js] => Array
                        (
                            [expected] => 46e390caaf3bf8981905de1548e614291ed940fe7670d61d7e2ae93d14b8dfaf9ae1120f5b83b1edea836529bdaea7a69fed4113b8fd5120d4a7d76530d58dae
                            [current] => 7cbb83a8d60bf7baf5bf48f6e20f6b4f42e9dfe6b92bce6daa37623f66e15486bbd8777349bc9e7da6deef8d6f8e94f3d4c7e054378a70f2edf8824b9bcfb0f0
                        )

                    [templates/index.php] => Array
                        (
                            [expected] => 387c1e81dbb9367b32903d216651ad0e066908dff125591561893af6fbe5af77a4c7cde71211c9dfcd1b090b49f9861058478260280d1f3cc9268671c42baa7b
                            [current] => 608b4b46cbf9b54125b86304d5233496c20be9cd2f2bd5833bf5489cfc480e338487b3e9d5e49de58510154692ccc514bc8ce4c85833ab532e1beb55caa41fac
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [img/app.png] => Array
                        (
                            [expected] => 
                            [current] => a9184792a581b73be98f1b98892c711851f38e25427ede1681e4c4094b3f1cd6a867d9bcc3693cfc20e376acd3e742552947d6c442e417e296cf351810452227
                        )

                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => d7c13790362626b8e7416c95ddc1228f49cc59d949ff79f617eac903b198e7e7feab7e7dc50a7875c91db31a10eaa0cd84f5e0163ef401c3b9a8e4268cef7a14
                        )

                )

        )

)

**Comment by icewind1991** [comment]
@LukasReschke I have no idea what to do with this

**Comment by LukasReschke** [comment]
Why do you use something from Git if this is already bundled with Nc11? This is something unsupported and will throw errors as expected.
