### ISSUE TITLE
Top bar disappears if logfile has no entries with a log level that is higher than the current log-level

### ISSUE THREAD

**Issue by aronovgj** [nextcloud/logreader#31]
This makes it impossible to change the log-level as the option is in that bar.

**Comment by moblaw** [comment]
Yes, I got same problem now

https://help.nextcloud.com/t/logging-admin-page-does-not-show-any-log-entry/5402

**Comment by KB7777** [comment]
NC 11, PHP7.1 -- the same problem :(

**Comment by nickvergessen** [comment]
@icewind1991 please backport this to 11.0.2 because the app is shipped and there are multiple reports coming in with this issue.

**Comment by icewind1991** [comment]
Backported
