### ISSUE TITLE
Audit log file fed but not displayed through the admin web interface 

### ISSUE THREAD

**Issue by oxlanech** [nextcloud/logreader#318]
### Steps to reproduce
1. Activate debug level logging (0) in config/config.php
2. Activate Audit Nextcloud app from the web administration panel 
3. Login and logout several times
4. Login back with an admin account and go to the administration panel: the login and logout requests are not displayed
5. However, these requests are logged in the audit.log file

### Expected behaviour
The content of the audit.log file should be displayed in the web administration logging panel

### Actual behaviour
Login or log out requests are not displayed on the web interface

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2

**Database:** Mysql

**PHP version:** 7

**Nextcloud version:** 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**List of activated apps:**
<details>
<summary>App list</summary>
Auditing / Logging 
</details>

**Nextcloud configuration:**

<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => 'owsk6pnizeou',
  'passwordsalt' => 'xxxxx'
  'secret' => 'xxxxx',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.intra.inet,
  ),
  'datadirectory' => '/home/nextclouduser',
  'dbtype' => 'mysql',
  'version' => '16.0.3.0',
  'overwrite.cli.url' => 'https://nextcloud.intra.inet',
  'dbname' => 'xxxx',
  'dbhost' => 'xxxx',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '',
  'installed' => true,
        'log_type' => 'file',
        'logfile' => 'nextcloud.log',
        'loglevel' => '0',
);
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox/60.0

**Operating system:** Microsoft Windows 10

#### Web server error log

<details>
<summary>Web server error log</summary>

No error in the error log
</details>

#### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"xxxx","level":0,"time":"August 16, 2019 10:12:45","remoteAddr":"10.100.20.19","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Log\\Rotate job with ID 20","userAgent":"Mozilla\/5.0 Gecko\/20100101 Firefox\/60.0","version":"16.0.3.0"}

```
</details>
<details>
<summary>Nextcloud audit log</summary>
```
{"reqId":"A2rPl1W4l4JQTIOih1aS","level":1,"time":"August 16, 2019 13:16:56","remoteAddr":"10.100.18.116","user":"Admin01","app":"admin_audit","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Login successful: \"Admin01\"","userAgent":"Mozilla\/5.0 (Windows 10 rv:58.0) Gecko\/20100101 Firefox\/60.0","version":"16.0.3.0"}
```
</details>

**Comment by GambaJo** [comment]
Same here (apache2, without docker).

**Comment by jmartin-oss** [comment]
Same problem. Tested on:
NC 15.0.14 with apache2 (no docker)
NC 17.0.2 with apache2 (no docker)

**Comment by jmartin-oss** [comment]
Tested also with NC 18.0.1 with apache2 (no docker) and still have the same problem

**Comment by GambaJo** [comment]
maybe the problem is not the logreader but the log itself. I think, the log is in JSON format. Maybe the JSON stucture in the log file is corrupt.

**Comment by jmartin-oss** [comment]
GambaJo, I don't think so the JSON structure is pretty the same compared to nextcloud.log.

I think that the problem could be because logreader is ignoring 'audit.log' file and only reading 'nextcloud.log' file, all the events in nextcloud.log are represented but audit.log ones are absent.

I tried to move audit.log file out of the cloud storage to /var/log/nextcloud/audit.log for avoiding permissions problem, locating it in the same place that nextcloud.log without success.

**Comment by GambaJo** [comment]
I updated NC to 18.0.1 and now I can see the log.

**Comment by jmartin-oss** [comment]
I updated some days ago to 18.0.1 and I still cannot view the logs.
Can you share the admin_audit section obtained from with the command: `occ config:list`

This is mine:
       "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "logfile": "\/var\/log\/nextcloud\/audit.log",
            "types": "logging"
        },

**Comment by jmartin-oss** [comment]
Updated to 18.0.3 and I still cannot see the audit log in the admin web interface.
Any idea?

**Comment by aproposnix** [comment]
I never had this issue until I updated to NC 20 b1-2

**Comment by vivek-kumar-004** [comment]
We're currently also facing issue with not being able to see the admin audit log in the logreader.
If we download the admin audit log and use the "Load logs..." feature for the logreader it displays the admin audit logs properly.

## 1. What's lacking
Looking at the logreader code, we see that it only looks at the configuration option: `logfile` to determine the file to read. This means that multiple files CANNOT be read.

The logfile can be configured with the config.php but its not very user convenient.

## 2. What we want
1. To select desired log file and display its content on the logreader app.
2. The ability to configure multiple log files for log reader and switch from reading one to another via UI.

![image](https://user-images.githubusercontent.com/62109167/107334329-95974400-6adc-11eb-809d-d0a87e7301c8.png)

**config.php**
```php
'additionalLogs' => [
	'Audit logs' => '/path/audit.log',
	'Any other logs' => '/path/other.log'
]
```

## 3. How we are planning to implement

	1. UI
		1. Radio buttons
			1. Add another component similar to ToggleEntry with radio button
			1. Nextcloud logs radio button will be the default selected and will always be visible.(this will be as per the 'logfile' in config.php)
			2. The other radio button options can be rendered by reading the additionalLogs array from config.php.
		2. On selecting the radio button, we need to make an API call to save the selectedLog setting in app_config table.
	2. Backend
		1. On get, we need to fetch the selected log from the app_config table and decide which log file needs to be read.
		2. By default, the Nextcloud log option will be selected.
		3. Additional logs array will be a key-value associative array in config.php
		4. Add an API to get all the additionalLogs to render the radio buttons.

**Comment by joshtrichards** [comment]
The `logreader` currently only accesses the `nextcloud.log`. The audit log, however, can be integrated by configuring it to also log there. That's how you end up with an integrated view of everything in the Web UI.

Try this in your `config.php` (adjusting the path to your own `nextcloud.log` path):

```
  'log.condition' => [
          'apps' => [ 'admin_audit'],
  ],
  'logfile_audit' => '/var/www/html/data/nextcloud.log',
```

And make sure you don't have any other stray `audit` related references in your `config.php`
