### ISSUE TITLE
Action Bar is Missing when there are no entries for selected levels

### ISSUE THREAD

**Issue by benbrummer** [nextcloud/logreader#33]
If you select different Levels. For Example Fatal + Error and there are no entries for these types. The Action Bar for Selecting Levels (Level App Message Time) is not shown anymore. So you can not select different Levels anymore. Only the Message "No server logs Everything is working fine" is shown.
![empty](https://cloud.githubusercontent.com/assets/24470839/21425166/d1174eee-c847-11e6-94a6-91433bcaa628.PNG)

**Comment by icewind1991** [comment]
Fix with https://github.com/nextcloud/logreader/commit/c77ee8186f61018afe78de41a4811e639e08edf9
