### ISSUE TITLE
Understanding of reqid

### ISSUE THREAD

**Issue by GAS85** [nextcloud/logreader#346]
Hello, I wrote simple script that will push some info in logs. And then I got this ticket https://github.com/GAS85/nextcloud_scripts/issues/1. I do create reqid as [random 20](https://github.com/GAS85/nextcloud_scripts/blob/cbda9a446564f57cdda35222b92b92e82014b2d6/nextcloud-preview.sh#L84) and I'm not sure if it is correct to nextcloud or not. Could you please give few hints how reqid should looks like and if I'm able to generate it randomly for outside scripts?

**Comment by icewind1991** [comment]
The code that generates them can be found here: https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Http/Request.php#L579-L595

**Comment by GAS85** [comment]
Thanks, so basically it is random 20 symbols from a-z, A-Z and 0-9 and fits to my:

    < /dev/urandom tr -dc A-Za-z0-9 | head -c20
