### ISSUE TITLE
Lock out by unsetting all log filters

### ISSUE THREAD

**Issue by SomeStrangeName** [nextcloud/logreader#35]
If you unset all filters in the logging view (no checkbox at any of the logging categories like error info and so on) the page shows: "No server logs Everything is working fine" and you will not have the option to check some check-boxes in the log table (header is not shown).

Using nextcloud 11 and logreader version 2.0.0

**Comment by SomeStrangeName** [comment]
With access to database use `update oc_appconfig set configvalue="11111" where appid="logreader" AND configkey="levels";` :)

**Comment by FriedCircuits** [comment]
I had the same thing app. The status bar at the top should always show regardless if there are entries or not. ;).

Thanks for SQL to set it back.

**Comment by icewind1991** [comment]
This is fixed by https://github.com/nextcloud/logreader/commit/c77ee8186f61018afe78de41a4811e639e08edf9
