### ISSUE TITLE
logreader app doesn't load

### ISSUE THREAD

**Issue by stanelie** [nextcloud/logreader#36]
Hello.

I enabled the logreader app and it is not showing up in the upper left app menu. It used to work, I just upgraded to Nextcloud 11 and I am unable to have the logreader app show up.

Thanks!

**Comment by JSoko** [comment]
You'll find it now under admin-> logging

**Comment by dolohow** [comment]
> You'll find it now under admin-> logging

When clicking the spinner is spinning the whole time and rsyslogd and journald processes takes 100% cpu time even when I close the page and the only way to make them disappear is to restart php-fpm process.

**Comment by stanelie** [comment]
Thanks @JSoko .
I would close this issue, but @dolohow appears to be experiencing an issue that could be filed under this ticket's title, so I will leave it open.

**Comment by pfofi** [comment]
Is this thread becoming a conglomeration for log issues? 😄 I have another one that could also be titled as "logreader app doesn't load".

After upgrading from NC 10.0.3 to 11.0.1 I did a probably superfluous thing and disabled the Log Reader app for any group but admin. Then all log entries disappeared. I can see the logfile getting bigger. but the Log Reader just shows "No server logs - Everything is working fine":

![no_server_logs](https://cloud.githubusercontent.com/assets/7479939/22852819/0039b39a-f045-11e6-9b2c-5010b7ed044e.png)
