### ISSUE TITLE
Proper icon for log reader app

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/logreader#38]
Currently it looks like this (the gear icon):

<img width="189" alt="bildschirmfoto 2017-01-24 um 11 47 54" src="https://cloud.githubusercontent.com/assets/245432/22260074/66fa75c2-e22d-11e6-8540-767004e4af9d.png">

Maybe @eppfel has a nice idea for a log icon :)

Stuff that I found: https://thenounproject.com/search/?q=log&i=565403 
or some inspiration from a reports collection: https://thenounproject.com/vikavld/collection/reports-administration/?oq=log&cidx=17

**Comment by MorrisJobke** [comment]
cc @skjnldsv ;)

**Comment by skjnldsv** [comment]
Something like that?
![image](https://cloud.githubusercontent.com/assets/14975046/22261275/8ff2b680-e26c-11e6-906d-98317da9f4a2.png)

**Comment by MorrisJobke** [comment]
I guess that's too complex. Just having some lines (3-5) and a dot in front should be enough.

**Comment by eppfel** [comment]
Not unique, but for a start we could use the logo from the versions app.

<img width="57" alt="bildschirmfoto 2017-01-25 um 11 38 07" src="https://cloud.githubusercontent.com/assets/1899308/22287334/c44457dc-e2f2-11e6-87e5-b50996fec017.png">

**Comment by jancborchardt** [comment]
@eppfel good call – want to prepare a pull request? :)

**Comment by jancborchardt** [comment]
Pull request at https://github.com/nextcloud/logreader/pull/49, using the Versions app icon as proposed by @eppfel :)
