### ISSUE TITLE
Nextcloud 20 Beta 3 Logging View

### ISSUE THREAD

**Issue by axheli** [nextcloud/logreader#383]
The View looks different then on Nextcloud 19 less organized in NC20

![image](https://user-images.githubusercontent.com/59488153/92620524-5c864980-f288-11ea-9914-67f8edbae9b3.png)

**Comment by MorrisJobke** [comment]
cc @skjnldsv @icewind1991 

For me this looks quite how it should, but I also rarely use the log app itself.

**Comment by skjnldsv** [comment]
I have no idea, never use nor maintained this app :shrug:

**Comment by axheli** [comment]
![image](https://user-images.githubusercontent.com/59488153/92749371-aab05100-f34b-11ea-80bd-6d325c1cc860.png)

thats how it looks on the older version

**Comment by axheli** [comment]
Looks like the logging has been fixed. 

![image](https://user-images.githubusercontent.com/59488153/94452725-7626fc80-0175-11eb-9705-72e10402eb37.png)
