### ISSUE TITLE
filter button gone

### ISSUE THREAD

**Issue by user1o1** [nextcloud/logreader#39]
when i deselected all kinds of logging entries, the filter button disappears. So i can´t activate them again.

Win10, Chrome & ie11, Nextcloud 11

![image](https://cloud.githubusercontent.com/assets/16254360/22260800/ca019ea6-e26a-11e6-831c-9a2195c3ef19.png)

**Comment by icewind1991** [comment]
Fixed by https://github.com/nextcloud/logreader/commit/c77ee8186f61018afe78de41a4811e639e08edf9 should be shipped with 11.0.2
