### ISSUE TITLE
Empty logview, unable to repick logs to show

### ISSUE THREAD

**Issue by DTseven** [nextcloud/logreader#41]
I accidentially unchecked the visibility boxes for all my logfiles. With unchecking the last one, the field to select them disappeared too.
I am now unable to see any logs and unable to select which ones to show.

Is there any workaround? Enabling and disabling in command line doesn't work.
Is there a way to reinstall?
Thanks in advance!

**Comment by 6triple8** [comment]
Seems to be a duplicate of #35 (includes workaround) and #39.
