### ISSUE TITLE
logreader displays the wrong time

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/logreader#42]
My logreader is not getting the right time region. My log settings for nextcloud are and even though the logfile directly displays the right time the logreader is 1 hour early. I can not find out why he is doing that.
```
  'logdateformat' => 'd.m.Y - H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 52428800,
  'loglevel' => 2,
  'logfile' => '/var/log/nextcloud/nextcloud.log',
```

**Comment by qswroot** [comment]
I have the same problem after having updated to version 11.0.3. All entries are displayed 2 hours ahead, although they are logged with the correct timestamp in the logfile.

  'log_type' => 'file',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 1,
  'syslog_tag' => 'Nextcloud',
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',

**Comment by icewind1991** [comment]
Can you check what the time value is for the entries in the file (something like `"time":"2017-07-03T18:43:09+02:00"`)

**Comment by mightyBroccoli** [comment]
"time":"2017 07 03 - 17:07:55" these are the timestamps in my logfiles

**Comment by qswroot** [comment]
My timestamps are "time":"July 04, 2017 13:31:29"

**Comment by qswroot** [comment]
IMHO this can be closed now, the proposed fix is working.
