### ISSUE TITLE
Page jumps to top of the list after loading additional entries

### ISSUE THREAD

**Issue by aronovgj** [nextcloud/logreader#43]
Reproduce:

1. Scroll down until older entries have to be loaded
2. New entries are loaded but you are brought back to the top of the list. So now you have to scroll all the way down again.

Expected: 

Don't jump to the top of the list, only load additional entries.

**Comment by tpscorpio** [comment]
I can verify this issue mentioned by aronovg.
Ubuntu 16.04.02 LTS server
Nextcloud 11.0.2.7
Log Reader 2.0

In the former version of Nextcloud (11.0.1) it worked without fault.

Expected: Solution as quickly as possible. Many thanks in advance to Robin.

**Comment by aronovgj** [comment]
Yes, right, should have mentioned it: I also noticed this issue after updating to 11.0.2

**Comment by enoch85** [comment]
I can confirm this as well on 11.0.2

**Comment by enoch85** [comment]
cc @MorrisJobke @icewind1991 Please :)

**Comment by icewind1991** [comment]
should be fixed in master.

Will tag a release once I'm back home where my signing keys are

**Comment by enoch85** [comment]
@icewind1991 When is this released?

**Comment by icewind1991** [comment]
Updated the stable11 branch to include this fix, should be bundled with the upcoming 11.0.3 server release
