### ISSUE TITLE
Empty page when clicking logging

### ISSUE THREAD

**Issue by StefanGebhardt** [nextcloud/logreader#436]
### Steps to reproduce
1. LogOn as admin
2. Clicking "Administration / Logging" (https://nextcloud.xxx.xxx/index.php/settings/admin/logging)

### Expected behaviour
See the logging

### Actual behaviour
Empty Page

### Server configuration

**Operating system**:
Unknown - Webspace all-inkl.com

**Web server:**
Unknown - Webspace all-inkl.com

**Database:**
MariaDB 10.5.6

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.6

**Where did you install Nextcloud from:**
all-inkl.com package

**List of activated apps:**

Enabled:  - accessibility: 1.6.0  - activity: 2.13.4  - admin_audit: 1.10.0  - analytics: 3.2.0  - bruteforcesettings: 2.0.1  - calendar: 2.1.3  - cloud_federation_api: 1.3.0  - comments: 1.10.0  - contactsinteraction: 1.1.0  - dashboard: 7.0.0  - dav: 1.16.2  - federatedfilesharing: 1.10.2  - files: 1.15.0  - files_downloadactivity: 1.9.0  - files_pdfviewer: 2.0.1  - files_rightclick: 0.17.0  - files_sharing: 1.12.2  - files_trashbin: 1.10.1  - files_versions: 1.13.0  - files_videoplayer: 1.9.0  - firstrunwizard: 2.9.0  - logreader: 2.5.0  - lookup_server_connector: 1.8.0  - nextcloud_announcements: 1.9.0  - notifications: 2.8.0  - oauth2: 1.8.0  - occweb: 0.0.7  - ownbackup: 19.9.0  - password_policy: 1.10.1  - photos: 1.2.3  - privacy: 1.4.0  - provisioning_api: 1.10.0  - recommendations: 0.8.0  - serverinfo: 1.10.0  - settings: 1.2.0  - sharebymail: 1.10.0  - support: 1.3.0  - survey_client: 1.8.0  - systemtags: 1.10.0  - text: 3.1.0  - theming: 1.11.0  - twofactor_backupcodes: 1.9.0  - updatenotification: 1.10.0  - user_status: 1.0.1  - viewer: 1.4.0  - weather_status: 1.0.0  - workflowengine: 2.2.0
Disabled:  - encryption  - federation  - files_external  - user_ldap  - user_usage_report

**Nextcloud configuration:**

{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "nextcloud.gabble.it"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "overwrite.cli.url": "http:\/\/nextcloud.gabble.it",        "dbtype": "mysql",        "version": "20.0.6.1",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "W1Wdn_",        "mysql.utf8mb4": true,        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "tempdirectory": "\/www\/htdocs\/w013d860\/nextcloud.gabble.it\/tmp\/",        "maintenance": false,        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_smtpmode": "smtp",        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "theme": "",        "loglevel": 2,        "syslog_tag": "Nextcloud",        "activity_expire_days": 32,        "trashbin_retention_obligation": "90, 120",        "updater.release.channel": "stable",        "filelocking.enabled": true,        "app_install_overwrite": [            "files_downloadactivity",            "admin_notifications",            "caniupdate",            "occweb",            "ownbackup",            "gpxedit"        ],        "updater.secret": "***REMOVED SENSITIVE VALUE***"    }}

### Client configuration
Every Browser (Safari, Firefox, ...)

**Operating system:**
MacOS

#### Nextcloud log (data/owncloud.log)

It's data/nextcloud.log(!)

{"reqId":"YBFCVqy4ddSW0Umes5vpNgAAAIo","level":2,"time":"2021-01-27T10:37:10+00:00","remoteAddr":"84.56.88.7","user":"--","app":"no app in context","method":"PROPFIND","url":"/remote.php/dav/files/Ulrike.Stefan/Bilder/Archiv/1967-1990%20Dias","message":"Temporary directory /www/htdocs/w013d860/nextcloud.gabble.it/tmp/ is not present or writable","userAgent":"--","version":"20.0.6.1"}
{"reqId":"YBFCVqy4ddSW0Umes5vpNwAAAJg","level":2,"time":"2021-01-27T10:37:10+00:00","remoteAddr":"84.56.88.7","user":"--","app":"no app in context","method":"PROPFIND","url":"/remote.php/dav/files/Ulrike.Stefan/Bilder/Archiv/1974-1981%20Bilder","message":"Temporary directory /www/htdocs/w013d860/nextcloud.gabble.it/tmp/ is not present or writable","userAgent":"--","version":"20.0.6.1"}

**Comment by joshtrichards** [comment]
This was awhile ago. Are you still experiencing this with newer versions?

**Comment by joshtrichards** [comment]
Closing due to age, but feel free to follow-up if still experiencing.
