### ISSUE TITLE
display the time in a quick and easy readable way

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/logreader#45]
in logreader 1.1.5 the time is displayed in an easy readable format like _"x minutes/hours ago"_ and when hovering, the tool-tip displays the exact time in an ISO-format.
this was excellent for a quick check whether everything works well!

but with logreader 2.0 this was changed, so every time i want to have a quick look at the logs i have to look for a clock first and then add the offset for the timezone... and the tool-tips (with the easy readable format) are pretty useless because i have to hover one entry after another.

_i have to say usually i'm not a fan of such easy readable formats. but in this case it makes sence._
but for sure downloaded logs should contain the exact time in an ISO-format.

if it is not possible to change to the old behavior, one practical suggestion to satisfy maybe both points of views:
**how about a trigger for the format of the displayed time, like the check-boxes for the log-levels?**

**Comment by DJCrashdummy** [comment]
**i found a kind of a workaround:**
open https://yourdomain.tld/nextcloud/index.php/apps/logreader to open the "old app-interface"; on the left bottom there is a settings-button like usual an there you can activate the _Relative Dates_. after that the relative dates are also displayed when you access the logs via the admin-menu.

...a pretty well hidden setting! ;-)

**Comment by icewind1991** [comment]
You can toggle the date display mode by clicking on the date

**Comment by DJCrashdummy** [comment]
thank you very much for the hint! - i feel a little bit dumb now... :-/
but as the cursor does not change, neither it is over the dates nor the column heading, this function is hard to "guess".

maybe this could be a very small but for some people useful improvement...
