### ISSUE TITLE
Logging does not load

### ISSUE THREAD

**Issue by asoliverez** [nextcloud/logreader#52]
### Steps to reproduce
1.Click on Admin/Logging

### Expected behaviour
Logging page should finish loading

### Actual behaviour
Loading icon displays and stays forever

### Server configuration

**Operating system**: Archlinux i386

**Web server:** Apache

**Database:** Mariadb

**PHP version:** 5.7

**Nextcloud version:** 11.0.3

**Where did you install Nextcloud from:** tar.gz

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.4
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.2.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - qownnotesapi: 17.3.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - documents
  - encryption
  - files_external
  - mail
  - user_external
  - user_ldap
  - user_saml

```

**Nextcloud configuration:**

```
{
    "system": {
        "datadirectory": "\/srv\/server\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "507895ccc101e",
        "maintenance": false,
        "theme": "",
        "asset-pipeline.enabled": false,
        "default_language": "es",
        "overwrite.cli.url": "\/owncloud",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "loglevel": 2,
        "forcessl": true,
        "log_type": "syslog",
        "logdateformat": "F d, Y H:i:s",
        "logfile": "",
        "syslog_tag": "Nextcloud",
        "trusted_domains": [
            "soliverez.com.ar"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "has_internet_connection": true,
        "check_for_working_htaccess": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "owncloud",
        "mail_domain": "soliverez.com.ar",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "apps_paths": [
            {
                "path": "\/srv\/server\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

```

### Client configuration
**Browser:**
Firefox
**Operating system:**
Manjaro
### Logs

**Comment by asoliverez** [comment]
The error log in journalctl shows:

`may 09 19:17:44 wega Nextcloud[11121]: {PHP} fopen(): Filename cannot be empty at /srv/server/www/owncloud/apps/logreader/lib/Controller/LogController.php#55
may 09 19:17:44 wega Nextcloud[11121]: {index} Exception: {"Exception":"Exception","Message":"Error while opening ","Code":0,"Trace":"#0 \/srv\/server\/www\/owncloud\/apps\/logreader\/lib\/Controller\/LogController.php(72): OCA\\LogReader\\Controller\\LogController->getLogIterator()\n#1 [internal function]: OCA\\LogReader\\Controller\\LogController->get(50, 0)\n#2 \/srv\/server\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#3 \/srv\/server\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#4 \/srv\/server\/www\/owncloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#5 \/srv\/server\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\LogReader\\\\C...', 'get', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#7 \/srv\/server\/www\/owncloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#8 \/srv\/server\/www\/owncloud\/lib\/base.php(1010): OC\\Route\\Router->match('\/apps\/logreader...')\n#9 \/srv\/server\/www\/owncloud\/index.php(40): OC::handleRequest()\n#10 {main}","File":"\/srv\/server\/www\/owncloud\/apps\/logreader\/lib\/Controller\/LogController.php","Line":59}`

**Comment by polcape** [comment]
Same problem... In the logging page don load anything, only the mooving circle

**Comment by sbr9150** [comment]
Check this out . It works for me.
[dont die when we cant decipher the logging time #53](https://github.com/nextcloud/logreader/pull/53)

**Comment by asoliverez** [comment]
That's not the solution in my case. It throws an exception when trying to open the log file, not when parsing a time.

**Comment by polcape** [comment]
Yes, I am solved the issue with the modify proposed.

**Comment by IKSGroth** [comment]
I have the same problem and it started after I set Nextcloud to log to the syslog. If the logreader is not capable of displaying syslog-entries, and I could live with that, it should display a message instead of "loading" forever.

**Comment by Luto73** [comment]
Same problem here after a distro upgrade from Debian 8 (jessy) to 9 (stretch). Maybe the updated PHP version? Don't know.

**Comment by mritzmann** [comment]
Maybe your `nextcloud.log` is to big? https://github.com/nextcloud/logreader/issues/719

**Comment by joshtrichards** [comment]
It's because you've changed your `log_type` to `syslog`. The log reader only supports the default `log_type` (`file`).
