### ISSUE TITLE
No log levels closing button

### ISSUE THREAD

**Issue by dariomkd5** [nextcloud/logreader#522]
![bug1](https://user-images.githubusercontent.com/85167787/121485940-fb370680-c9d0-11eb-9e9f-13c44a0526ac.PNG)
If I click anywhere on the screen it doesn't close.

**Comment by Valdnet** [comment]
In this case, the menu for levels should close after clicking outside of its area. This is a bug that needs to be fixed.

**Comment by joshtrichards** [comment]
Not sure what version this was being reported for, but both of these menus have since been fixed.

We can close this out.

**Comment by susnux** [comment]
Fixed for at least NC27, NC26 and master.
