### ISSUE TITLE
Double scroll bar in log view

### ISSUE THREAD

**Issue by despens** [nextcloud/logreader#536]
### Steps to reproduce
1. Go to /settings/admin/logging

### Expected behaviour
Only a single scroll bar should be used

### Actual behaviour
A nested scrollbar appears:

![image](https://user-images.githubusercontent.com/571494/93459744-79eb9100-f8e2-11ea-8b2f-cfcd6e4b45e9.png) ![image](https://user-images.githubusercontent.com/571494/93459807-9687c900-f8e2-11ea-9c8b-22f4e68725cd.png)

The log view's "outer scrollbar" is only allowing to scroll a few pixels up and down.

### Server configuration

**Operating system:** official nextcloud docker

**Web server:** official nextcloud docker

**Database:** Postgresql 12

**PHP version:** official nextcloud docker

**Nextcloud version:** 19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 19.0.1

**Where did you install Nextcloud from:** official docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** primary object storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 80

**Operating system:** Ubuntu 18.08

**Comment by susnux** [comment]
Fixed at least since Nextcloud 25
