### ISSUE TITLE
Cant download from apps.owncloud.com

### ISSUE THREAD

**Issue by mr-flibble** [nextcloud/logreader#55]
Hello, if I try download app from:
https://apps.owncloud.com/content/show.php?content=170871
using Download button - Im redirected to https://apps.owncloud.com/CONTENT/content-files/174834-jj%3Cimg%20src= url with 404 file not found message

Or upgrading app from owncloud 
![image](https://cloud.githubusercontent.com/assets/5197625/26393286/a9803676-4069-11e7-824b-6caf6e2392ed.png)

**Comment by jancborchardt** [comment]
@icewind1991 could you publish the app at https://apps.nextcloud.com/ and update the link in the readme? :) cc @MorrisJobke @rullzer

**Comment by icewind1991** [comment]
apps.owncloud.com is no longer active

**Comment by jancborchardt** [comment]
@icewind1991 ah ok - I was trying to install it on my Nextcloud 12, but probably didn't have it cause I update through git.
