### ISSUE TITLE
There is no update for NC 22.1.1

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/logreader#569]
In the NC 22.1.1 version, there is no Logreader after the fixes. There should be an update for the new Nextcloud version and for versions 21 and 20.

**Comment by szaimen** [comment]
https://github.com/nextcloud/logreader/releases/tag/v22.1.1

**Comment by Valdnet** [comment]
@szaimen The new version of Log Reader 22.0.0 was released on August 26, 2021. NC 21.1.1 was released on August 27, 2001, which still contains Log Reader version 2.7.0.

Shouldn't a backport be done for NC 22, 21 and 20 versions?

**Comment by Valdnet** [comment]
ping @icewind1991 @szaimen

**Comment by szaimen** [comment]
Actually, I don't know if thats backportable. ping @icewind1991 on that.

**Comment by Valdnet** [comment]
ping @icewind1991
