### ISSUE TITLE
There are many strings at Transifex which should not be translated

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/logreader#65]
Currently there are 38 strings listed at Transifex.

17 of them should not be there.

Comment of @nickvergessen 

> everything until "bubbled" (15) is from a bug of our language string detection....

Please fix this.

**Comment by icewind1991** [comment]
@MorrisJobke is there anyway to exclude the 'build' directory from getting picked up for translation?

The same problem exists in the groupfolders app

**Comment by MorrisJobke** [comment]
Let me check that, but yes it should be possible.

**Comment by MorrisJobke** [comment]
Added and the transifex is also already updated: https://github.com/nextcloud/docker-ci/commit/8d37cda1f0be3a67767f9089998d4ccbb9f2bbe6

**Comment by ynott** [comment]
:+1:
