### ISSUE TITLE
Logreader does not show logs even when logs are existent in logfile

### ISSUE THREAD

**Issue by Greek64** [nextcloud/logreader#67]
The logreader does not show the configured loglevel logs, even if the logs are existent in the logfile.

### Steps to reproduce
1. Enable "Debug" loglevel in logreader and let it fill the log for a while
2. Make sure  to produce a few "Warning" logs
3. Disable again "Debug" Llglevel and set "Warning" as highest loglevel in logreader

### Expected behaviour
Show only logs with a loglevel of "Warning" or higher

### Actual behaviour
No logs show up at all, even though a manual look inside the logfile confirms that the logs exist.

**Operating system**: Docker Nextcloud
**PHP version:** 7.1.13
**Nextcloud version:** 12.0.5
**Logread version:** 2.0.0

I guess the logreader just checks the last X logs and shows them if necessary, but for a logread app I'm expecting it to check the whole log, not just the tip of the iceberg.

**Comment by susnux** [comment]
I could neither reproduce with Nextcloud 26 or 27.
With Nextcloud 28 this is fixed by https://github.com/nextcloud/logreader/pull/936
