### ISSUE TITLE
Scrolling doesn't fetch next page (again)

### ISSUE THREAD

**Issue by danielb42** [nextcloud/logreader#744]
Since upgrading to Nextcloud 24 the Log Viewer shows only the last 50 events. Nothing happens when scrolling to the end of the page. There are continious requests to `/poll` visible in the browser debugging/network tools, but they all take 20.0 seconds and return without any data (http 200 though).

**Comment by git-ikeda** [comment]
It’s the same.  Combined with the bug of “Trusted domain error. " xxx.xxx.xxx.xxx " tried to access using "xxx.xxx.xxx.xxx" as host.”, Nextcloud logs only displays 1 hour ago.
https://github.com/nextcloud/server/issues/32599

**Comment by joshtrichards** [comment]
I'm unable to reproduce this (even in latest v24).

Can you confirm you're still experiencing this?

The `/poll` is for the live updating only AFAIK. For traversing existing log entries the requests are all via `/get` and `/search` (with offset ranges attached as parameters). These requests should show up on your browser console.

If you're still experiencing this, please verify in a different browser (preferably one without any extensions enabled) to help identify if it's browser specific or an interaction with an extension. Thanks.

**Comment by danielb42** [comment]
Hi Josh, I'm on v26 meanwhile and its logreader is working again. IIRC it was alright after upgrading to v25.

**Comment by git-ikeda** [comment]
After upgrading to some version, it was fixed.
There is no problem with the current v26.0.1.
