### ISSUE TITLE
Log filter does not work in NC14.0.2

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/logreader#78]
Nextcloud server 14.0.2
ubuntu 16.04.5
php 7.0.32
Log Reader 2.0.0

when I enter a word in the filter then it shows an error:
"Error	PHP	stripos() expects parameter 1 to be string, array given at /var/www/html/nextcloud/apps/logreader/lib/Log/SearchFilter.php#55"

**Comment by tsmeets2** [comment]
I have the same error in NC14.0.3

**Comment by LarsLWO** [comment]
Same issue:

> stripos() expects parameter 1 to be string, array given at /var/www/html/apps/logreader/lib/Log/SearchFilter.php#55

Some specs:

> Version: 14.0.3.0
> PHP Version: 7.2.11
> Database / pgsql PostgreSQL 10.5 (Debian 10.5-2.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

**Comment by JochenHWezel** [comment]
I experience this same error with Nextcloud 14.0.4
