### ISSUE TITLE
Load log file and changing logging level do not work

### ISSUE THREAD

**Issue by luyuanerp** [nextcloud/logreader#788]
stable24 branch
1. Click Load log file, select the log file, the log file will not be loaded. Error in chrome console.
2. Logs are not re-loaded after changing logging level, and there is an error in the chrome console.

<img width="471" alt="QQ20220927-084553@2x" src="https://user-images.githubusercontent.com/75401343/192405819-c3a26e81-29c6-47e9-a144-698a81012ed0.png">

**Comment by Antreesy** [comment]
Last version of Logreader written in react is Nextcloud 27.1.11 (End of life was at 2024-06-25)
