### ISSUE TITLE
After update from nc12 to nc13 logreader ignores logtimezone for display

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/logreader#79]
I did an update from 12.0.6 to 13.0.7 and today i have noticed that the time display 
in logreader is in UTC.
In the logfile the time is correct!

So for example in the logfile > 2018-10-19T17:15:30+02:00
shows up in logreader as > 2018-10-19T15:15:30+00:00

'logtimezone' => 'Europe/Berlin', in config.php

**Comment by susnux** [comment]
I could not reproduce on Nextcloud 27 and for Nextcloud 28 we use a new UI.
Please reopen if you still experience this issue
