### ISSUE TITLE
2 entries in Apps Store

### ISSUE THREAD

**Issue by tessus** [nextcloud/logreader#8]
There are 2 log reader apps in the store:

![screen shot 2015-10-17 at 0 13 35](https://cloud.githubusercontent.com/assets/223439/10556949/099c0d88-7464-11e5-86cd-2bc93e7d76de.png)

![screen shot 2015-10-17 at 0 13 17](https://cloud.githubusercontent.com/assets/223439/10556950/0efbf52c-7464-11e5-9eec-c178de4c41f8.png)

Any idea what's going on?

**Comment by icewind1991** [comment]
One of them is your local install and the other one from the store, not sure why they show up seperate

**Comment by tessus** [comment]
Wait, this makes no sense. I installed 1.0.0 via the store and then upgraded it to 1.0.1. Then a second Log Reader app (logreader) appears in the store. Also, please note that one is named `Log Reader` and the other `logreader`.

**Comment by cdamken** [comment]
"round robin" :smile:
